using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading;
using System.Windows.Forms;
using Paster.Core;

namespace Paster.Windows
{
    internal sealed class WindowsPlatform : NativeWindow, ITextCapturePlatform, IDisposable
    {
        private const uint MOD_ALT=1, MOD_CONTROL=2, MOD_SHIFT=4, MOD_WIN=8, MOD_NOREPEAT=0x4000, WM_HOTKEY=0x0312, KEYEVENTF_UNICODE=4, KEYEVENTF_KEYUP=2, KEYEVENTF_EXTENDEDKEY=1;
        private const int HOT_CAPTURE=1, HOT_PASTE=2, HOT_CANCEL=3, HOT_WINDOWS_PASTE=4; private readonly PasterConfig config; private string registrationError; private volatile bool inputAvailable=true;
        private const int WH_KEYBOARD_LL=13, WM_KEYDOWN=0x100, WM_KEYUP=0x101, WM_SYSKEYDOWN=0x104, WM_SYSKEYUP=0x105; private const uint LLKHF_INJECTED=0x10, WM_CLIPBOARDUPDATE=0x031D, CF_UNICODETEXT=13;
        private readonly Paster.Core.Shortcut[] shortcuts=new Paster.Core.Shortcut[HOT_CANCEL+1]; private readonly bool[] latched=new bool[HOT_CANCEL+1]; private readonly LowLevelKeyboardProc hookProc; private IntPtr hook; private volatile int physicalKeyPresses; private int transferKeyBaseline; private volatile bool windowsPasteHeld; private bool pasteKeyDown; private volatile bool typeClipboardOnPaste;
        public event Action CaptureRequested; public event Action<bool> PasteRequested; public event Action CancelRequested;
        public WindowsPlatform(PasterConfig c) { config = c; DisablePowerThrottling(); CreateHandle(new CreateParams()); Register(config.CaptureShortcut, HOT_CAPTURE); Register(config.PasteShortcut, HOT_PASTE); Register(config.CancelShortcut, HOT_CANCEL); typeClipboardOnPaste=IsClipboardFormatAvailable(CF_UNICODETEXT); AddClipboardFormatListener(Handle); hookProc=KeyboardHook; hook=SetWindowsHookEx(WH_KEYBOARD_LL,hookProc,GetModuleHandle(null),0); if (hook==IntPtr.Zero) AddRegistrationError("Keyboard hook installation failed (error "+Marshal.GetLastWin32Error()+"); shortcuts require the key to be pressed last."); }
        public string RegistrationError { get { return registrationError; } }
        public IntPtr ForegroundWindow { get { return GetForegroundWindow(); } }
        public uint ClipboardSequence { get { return GetClipboardSequenceNumber(); } }
        public bool IsInputAvailable { get { return inputAvailable; } }
        // The hook counts only physical key presses, so our own injected typing can never look like a user interruption.
        public bool IsUserInterruptionRequested { get { return (hook!=IntPtr.Zero ? physicalKeyPresses!=transferKeyBaseline : UserKeyDown()) || MouseButtonDown(); } }
        // Typing while the shortcut is still physically held lets the held (and auto-repeating) modifiers turn typed text into application shortcuts.
        public bool WaitForPasteShortcutRelease() { Paster.Core.Shortcut paste=Paster.Core.Shortcut.Parse(config.PasteShortcut); WaitWhile(delegate { return ModifiersDown() || windowsPasteHeld || (GetAsyncKeyState((int)paste.Key)&0x8000)!=0; },5000); transferKeyBaseline=physicalKeyPresses; return !ModifiersDown() && !windowsPasteHeld && (GetAsyncKeyState((int)paste.Key)&0x8000)==0; }
        public bool SendCopyShortcut() { Paster.Core.Shortcut capture=Paster.Core.Shortcut.Parse(config.CaptureShortcut); bool captureUsesCopy=capture.Modifiers==MOD_CONTROL && capture.Key==0x43; if(captureUsesCopy) UnregisterHotKey(Handle,HOT_CAPTURE); try { if (!ReleaseModifiers()) return false; if (!SendKey(0x11, false)) return false; if (!SendKey(0x43, false)) { SendKey(0x11, true); return false; } if (!SendKey(0x43, true)) { SendKey(0x11, true); return false; } return SendKey(0x11, true); } finally { if(captureUsesCopy) Register(config.CaptureShortcut,HOT_CAPTURE); } }
        public bool TryReadClipboard(out string text) { text = null; try { if (Clipboard.ContainsText(TextDataFormat.UnicodeText)) { text = Clipboard.GetText(TextDataFormat.UnicodeText); return true; } } catch { } return false; }
        // Builds the whole batch as one SendInput call: Windows inserts it atomically, and the per-call cost is paid once per batch instead of once per character.
        // Characters that would need Shift, Ctrl, or Alt are sent as Unicode instead, so typing never presses a modifier: rapid Shift taps
        // trigger the Sticky Keys prompt (also on RDP hosts), and synthesized modifiers can combine with keys into application shortcuts.
        // Home and Delete are extended keys: without the flag and scan code, RDP clients map them to numpad 7 and "." when NumLock is on.
        public bool SendText(string text, bool codeMode) { if (text.Length == 0) return true; List<TypedKey> keys=CodeTyping.Expand(text,codeMode); INPUT[] inputs=new INPUT[keys.Count*2]; int count=0; for (int i=0; i<keys.Count; i++) { switch (keys[i].Action) { case KeyAction.Enter: AddKeyPair(inputs,ref count,0x0D,0x1C,0); break; case KeyAction.Tab: AddKeyPair(inputs,ref count,0x09,0x0F,0); break; case KeyAction.Escape: AddKeyPair(inputs,ref count,0x1B,0x01,0); break; case KeyAction.Home: AddKeyPair(inputs,ref count,0x24,0x47,KEYEVENTF_EXTENDEDKEY); break; case KeyAction.Delete: AddKeyPair(inputs,ref count,0x2E,0x53,KEYEVENTF_EXTENDEDKEY); break; default: char ch=keys[i].Character; short mapped=VkKeyScan(ch); if (mapped != -1 && (mapped & 0xff00) == 0) AddKeyPair(inputs,ref count,(ushort)mapped,0,0); else AddKeyPair(inputs,ref count,0,ch,KEYEVENTF_UNICODE); break; } } SendBatch(inputs,count,"keyboard input"); return true; }
        private static void AddKeyPair(INPUT[] inputs, ref int count, ushort key, ushort scan, uint flags) { inputs[count++]=CreateInput(key,scan,flags); inputs[count++]=CreateInput(key,scan,flags|KEYEVENTF_KEYUP); }
        // Windows 11 ignores timer-resolution requests from processes without visible windows unless they opt out of power throttling.
        private static void DisablePowerThrottling() { PROCESS_POWER_THROTTLING_STATE state=new PROCESS_POWER_THROTTLING_STATE(); state.Version=1; state.ControlMask=0x1|0x4; state.StateMask=0; try { SetProcessInformation(GetCurrentProcess(),4,ref state,Marshal.SizeOf(typeof(PROCESS_POWER_THROTTLING_STATE))); } catch (EntryPointNotFoundException) { } }
        // The default ~15.6 ms timer tick would stretch every batch delay; request 1 ms only while a transfer runs.
        public static void SetHighResolutionTimer(bool enabled) { if (enabled) timeBeginPeriod(1); else timeEndPeriod(1); }
        private static INPUT CreateInput(ushort key, ushort scan, uint flags) { INPUT input=new INPUT(); input.type=1; input.ki.wVk=key; input.ki.wScan=scan; input.ki.dwFlags=flags; return input; }
        private void SendBatch(INPUT[] inputs, int count, string kind) { if (SendInputBatch((uint)count,inputs,Marshal.SizeOf(typeof(INPUT))) != (uint)count) { inputAvailable=false; throw InputError(kind); } }
        private static Win32Exception InputError(string kind) { int code=Marshal.GetLastWin32Error(); return new Win32Exception(code, "Windows rejected "+kind+" (error "+code+")"); }
        private bool SendKey(ushort key, bool release) { INPUT i=new INPUT(); i.type=1; i.ki.wVk=key; i.ki.dwFlags=release ? KEYEVENTF_KEYUP : 0; bool sent=SendInput(1,ref i,Marshal.SizeOf(typeof(INPUT))) == 1; if(!sent) inputAvailable=false; return sent; }
        private bool ReleaseModifiers() { WaitWhile(ModifiersDown,5000); return !ModifiersDown(); }
        private static void WaitWhile(Func<bool> condition, int timeoutMilliseconds) { Stopwatch elapsed=Stopwatch.StartNew(); while (elapsed.ElapsedMilliseconds < timeoutMilliseconds && condition()) Thread.Sleep(5); }
        private static bool ModifiersDown() { return (GetAsyncKeyState(0x11)&0x8000)!=0 || (GetAsyncKeyState(0x12)&0x8000)!=0 || (GetAsyncKeyState(0x10)&0x8000)!=0 || (GetAsyncKeyState(0x5B)&0x8000)!=0 || (GetAsyncKeyState(0x5C)&0x8000)!=0; }
        private bool UserKeyDown() { Paster.Core.Shortcut paste=Paster.Core.Shortcut.Parse(config.PasteShortcut); for (int key = 1; key <= 0xFE; key++) { if (IsMouseButton(key) || key == (int)paste.Key || (key == 0x10 || key == 0xA0 || key == 0xA1) && (paste.Modifiers & MOD_SHIFT) != 0 || (key == 0x11 || key == 0xA2 || key == 0xA3) && (paste.Modifiers & MOD_CONTROL) != 0 || (key == 0x12 || key == 0xA4 || key == 0xA5) && (paste.Modifiers & MOD_ALT) != 0 || (key == 0x5B || key == 0x5C) && (paste.Modifiers & MOD_WIN) != 0) continue; if ((GetAsyncKeyState(key) & 0x8000) != 0) return true; } return false; }
        private static bool IsMouseButton(int key) { return key==0x01 || key==0x02 || key==0x04 || key==0x05 || key==0x06; }
        private static bool MouseButtonDown() { return (GetAsyncKeyState(0x01)&0x8001)!=0 || (GetAsyncKeyState(0x02)&0x8001)!=0 || (GetAsyncKeyState(0x04)&0x8001)!=0 || (GetAsyncKeyState(0x05)&0x8001)!=0 || (GetAsyncKeyState(0x06)&0x8001)!=0; }
        private void Register(string value, int id) { Paster.Core.Shortcut s=Paster.Core.Shortcut.Parse(value); shortcuts[id]=s; if (!RegisterHotKey(Handle,id,s.Modifiers|MOD_NOREPEAT,s.Key)) AddRegistrationError("Shortcut registration failed for "+value+"."); }
        private void AddRegistrationError(string error) { registrationError=String.IsNullOrEmpty(registrationError)?error:registrationError+" "+error; }
        // RegisterHotKey fires only when the key arrives after all modifiers. This hook covers the other order:
        // the key is already held and the final modifier completes the chord. Injected input (our own typing) is ignored.
        private IntPtr KeyboardHook(int code, IntPtr wParam, IntPtr lParam)
        {
            if (code >= 0) { KBDLLHOOKSTRUCT k=(KBDLLHOOKSTRUCT)Marshal.PtrToStructure(lParam,typeof(KBDLLHOOKSTRUCT)); int msg=wParam.ToInt32(); bool down=msg==WM_KEYDOWN||msg==WM_SYSKEYDOWN; if ((k.flags & LLKHF_INJECTED)==0 && (down||msg==WM_KEYUP||msg==WM_SYSKEYUP)) { if (down) physicalKeyPresses++; int vk=(int)k.vkCode; uint mods=CurrentModifiers(vk,down); if (down) TrackRemoteCopy(vk,mods); if (vk==0x56 && HandleWindowsPaste(down,mods)) return (IntPtr)1; bool modifierPressed=down && ModifierFlag(vk)!=0; for (int id=HOT_CAPTURE; id<=HOT_CANCEL; id++) { Paster.Core.Shortcut s=shortcuts[id]; if (s==null) continue; bool complete=mods==s.Modifiers && IsDown((int)s.Key,vk,down); if (!complete) { latched[id]=false; continue; } if (latched[id]) continue; latched[id]=true; if (modifierPressed) PostMessage(Handle,WM_HOTKEY,(IntPtr)id,IntPtr.Zero); } } }
            return CallNextHookEx(hook,code,wParam,lParam);
        }
        // A fresh Ctrl+V into a listed app (Remote Desktop by default) is swallowed and typed instead, but only while the clipboard holds text
        // copied locally; everywhere else, and after a copy inside the remote session, it stays a normal paste. The swallowed press (repeats
        // and key-up included) never reaches the remote or the async key state, so windowsPasteHeld tracks it until the physical key-up.
        private bool HandleWindowsPaste(bool down, uint mods) { if (!down) { pasteKeyDown=false; if (!windowsPasteHeld) return false; windowsPasteHeld=false; return true; } bool repeat=pasteKeyDown; pasteKeyDown=true; if (windowsPasteHeld) return true; if (repeat || mods!=MOD_CONTROL || !typeClipboardOnPaste || !IsTypeOnPasteTarget()) return false; windowsPasteHeld=true; PostMessage(Handle,WM_HOTKEY,(IntPtr)HOT_WINDOWS_PASTE,IntPtr.Zero); return true; }
        // A physical copy or cut inside the remote session means the user now wants the remote clipboard there, not the local text.
        private void TrackRemoteCopy(int vk, uint mods) { if ((mods==MOD_CONTROL && (vk==0x43 || vk==0x58 || vk==0x2D) || mods==MOD_SHIFT && vk==0x2E) && IsTypeOnPasteTarget()) typeClipboardOnPaste=false; }
        // Clipboard changes made while a listed app is in front come from the remote session (redirection) and paste natively; local text changes are typed.
        private void OnClipboardUpdate() { typeClipboardOnPaste=IsClipboardFormatAvailable(CF_UNICODETEXT) && !IsTypeOnPasteTarget(); }
        // Runs on the transfer worker. The dialog is topmost and forced to the foreground (the paste keypress went to another app); it closes as
        // Cancel on the cancel shortcut or after two minutes, so a dialog hidden behind a full-screen client cannot block Paster indefinitely.
        // After a non-cancel answer the target is reactivated and the keys or buttons used to answer are released before typing can start.
        public TransferChoice ConfirmTransfer(TransferPrompt prompt)
        {
            TransferChoice choice=TransferChoice.Cancel;
            using (Form f=new Form())
            {
                f.Text="Paster"; f.FormBorderStyle=FormBorderStyle.FixedDialog; f.StartPosition=FormStartPosition.CenterScreen; f.TopMost=true; f.ShowInTaskbar=false; f.MinimizeBox=false; f.MaximizeBox=false; f.ClientSize=new System.Drawing.Size(460,150);
                Label text=new Label(); text.Text=prompt.Message; text.Left=15; text.Top=15; text.AutoSize=true; text.MaximumSize=new System.Drawing.Size(430,0); f.Controls.Add(text);
                Button primary=new Button(), cancel=new Button(); primary.Text=prompt.CanResume?"&Resume":"&Type"; primary.DialogResult=prompt.CanResume?DialogResult.Yes:DialogResult.OK; cancel.Text="Cancel"; cancel.DialogResult=DialogResult.Cancel;
                Button[] buttons=prompt.CanResume ? new Button[] { primary, new Button(), cancel } : new Button[] { primary, cancel }; if (prompt.CanResume) { buttons[1].Text="&Start over"; buttons[1].DialogResult=DialogResult.OK; }
                int buttonTop=Math.Max(110,text.PreferredHeight+30); f.ClientSize=new System.Drawing.Size(460,buttonTop+40);
                for (int i=0; i<buttons.Length; i++) { buttons[i].Width=95; buttons[i].Top=buttonTop; buttons[i].Left=f.ClientSize.Width-15-(buttons.Length-i)*105+10; f.Controls.Add(buttons[i]); }
                f.AcceptButton=primary; f.CancelButton=cancel; f.Shown+=delegate { ForceForeground(f.Handle); primary.Focus(); };
                System.Windows.Forms.Timer expiry=new System.Windows.Forms.Timer(); expiry.Interval=1000; int remaining=120; expiry.Tick+=delegate { if (prompt.Cancellation.IsCancellationRequested || --remaining<=0) { expiry.Stop(); f.DialogResult=DialogResult.Cancel; } }; expiry.Start();
                DialogResult result; try { result=f.ShowDialog(); } finally { expiry.Dispose(); } choice=result==DialogResult.Yes ? TransferChoice.Resume : result==DialogResult.OK ? TransferChoice.Start : TransferChoice.Cancel;
            }
            if (choice==TransferChoice.Cancel) return choice;
            WaitWhile(AnswerKeysDown,5000);
            ForceForeground(prompt.TargetWindow); WaitWhile(delegate { return GetForegroundWindow()!=prompt.TargetWindow; },1000);
            MouseButtonDown(); transferKeyBaseline=physicalKeyPresses; return choice;
        }
        private static bool AnswerKeysDown() { int[] keys={0x01,0x02,0x04,0x0D,0x20,0x12,0x52,0x53,0x54}; for (int i=0; i<keys.Length; i++) if ((GetAsyncKeyState(keys[i])&0x8000)!=0) return true; return false; }
        // Windows only lets the process that received the last input take the foreground; briefly sharing the foreground thread's input state lifts that.
        private static void ForceForeground(IntPtr window) { uint ignored; uint foregroundThread=GetWindowThreadProcessId(GetForegroundWindow(),out ignored), current=GetCurrentThreadId(); bool attached=foregroundThread!=0 && foregroundThread!=current && AttachThreadInput(current,foregroundThread,true); try { SetForegroundWindow(window); BringWindowToTop(window); } finally { if (attached) AttachThreadInput(current,foregroundThread,false); } }
        private bool IsTypeOnPasteTarget() { return IsRemoteWindow(GetForegroundWindow()); }
        public bool IsRemoteWindow(IntPtr window) { return config.IsTypeOnPasteApp(ProcessPath(window),WindowTitle(window)); }
        private static string WindowTitle(IntPtr window) { StringBuilder title=new StringBuilder(512); return GetWindowText(window,title,title.Capacity)>0 ? title.ToString() : null; }
        private static string ProcessPath(IntPtr window) { uint pid; GetWindowThreadProcessId(window,out pid); if (pid==0) return null; IntPtr process=OpenProcess(0x1000,false,pid); if (process==IntPtr.Zero) return null; try { StringBuilder path=new StringBuilder(1024); int size=path.Capacity; return QueryFullProcessImageName(process,0,path,ref size) ? path.ToString() : null; } finally { CloseHandle(process); } }
        private static uint CurrentModifiers(int vk, bool down) { return (IsDown(0xA2,vk,down)||IsDown(0xA3,vk,down)?MOD_CONTROL:0)|(IsDown(0xA0,vk,down)||IsDown(0xA1,vk,down)?MOD_SHIFT:0)|(IsDown(0xA4,vk,down)||IsDown(0xA5,vk,down)?MOD_ALT:0)|(IsDown(0x5B,vk,down)||IsDown(0x5C,vk,down)?MOD_WIN:0); }
        private static uint ModifierFlag(int vk) { if (vk==0x11||vk==0xA2||vk==0xA3) return MOD_CONTROL; if (vk==0x10||vk==0xA0||vk==0xA1) return MOD_SHIFT; if (vk==0x12||vk==0xA4||vk==0xA5) return MOD_ALT; if (vk==0x5B||vk==0x5C) return MOD_WIN; return 0; }
        private static bool IsDown(int key, int vk, bool down) { return key==vk ? down : (GetAsyncKeyState(key)&0x8000)!=0; }
        protected override void WndProc(ref Message m) { if (m.Msg==WM_CLIPBOARDUPDATE) OnClipboardUpdate(); else if (m.Msg==WM_HOTKEY) { int id=m.WParam.ToInt32(); if(id==HOT_CAPTURE && CaptureRequested!=null) CaptureRequested(); else if(id==HOT_PASTE && PasteRequested!=null) PasteRequested(false); else if(id==HOT_WINDOWS_PASTE && PasteRequested!=null) PasteRequested(config.CodeModeForRemotePaste); else if(id==HOT_CANCEL && CancelRequested!=null) CancelRequested(); } base.WndProc(ref m); }
        public void Dispose() { RemoveClipboardFormatListener(Handle); if (hook!=IntPtr.Zero) { UnhookWindowsHookEx(hook); hook=IntPtr.Zero; } UnregisterHotKey(Handle,HOT_CAPTURE); UnregisterHotKey(Handle,HOT_PASTE); UnregisterHotKey(Handle,HOT_CANCEL); DestroyHandle(); }
        [StructLayout(LayoutKind.Sequential)] private struct INPUT { public uint type; public KEYBDINPUT ki; private uint padding1; private uint padding2; } [StructLayout(LayoutKind.Sequential)] private struct KEYBDINPUT { public ushort wVk,wScan; public uint dwFlags,time; public UIntPtr dwExtraInfo; }
        [DllImport("user32.dll")] private static extern uint GetWindowThreadProcessId(IntPtr hWnd,out uint processId); [DllImport("kernel32.dll")] private static extern IntPtr OpenProcess(uint access,bool inherit,uint processId); [DllImport("kernel32.dll", CharSet=CharSet.Unicode, EntryPoint="QueryFullProcessImageNameW")] private static extern bool QueryFullProcessImageName(IntPtr process,uint flags,StringBuilder path,ref int size); [DllImport("kernel32.dll")] private static extern bool CloseHandle(IntPtr handle);
        [DllImport("user32.dll", CharSet=CharSet.Unicode)] private static extern int GetWindowText(IntPtr hWnd,StringBuilder text,int maxCount); [DllImport("user32.dll")] private static extern bool AddClipboardFormatListener(IntPtr hWnd); [DllImport("user32.dll")] private static extern bool RemoveClipboardFormatListener(IntPtr hWnd); [DllImport("user32.dll")] private static extern bool IsClipboardFormatAvailable(uint format);
        [DllImport("user32.dll")] private static extern bool SetForegroundWindow(IntPtr hWnd); [DllImport("user32.dll")] private static extern bool BringWindowToTop(IntPtr hWnd); [DllImport("user32.dll")] private static extern bool AttachThreadInput(uint attach,uint attachTo,bool enable); [DllImport("kernel32.dll")] private static extern uint GetCurrentThreadId();
        [StructLayout(LayoutKind.Sequential)] private struct PROCESS_POWER_THROTTLING_STATE { public uint Version,ControlMask,StateMask; }
        [DllImport("kernel32.dll")] private static extern IntPtr GetCurrentProcess(); [DllImport("kernel32.dll")] private static extern bool SetProcessInformation(IntPtr process,int informationClass,ref PROCESS_POWER_THROTTLING_STATE information,int size); [DllImport("winmm.dll")] private static extern uint timeBeginPeriod(uint period); [DllImport("winmm.dll")] private static extern uint timeEndPeriod(uint period);
        [StructLayout(LayoutKind.Sequential)] private struct KBDLLHOOKSTRUCT { public uint vkCode,scanCode,flags,time; public UIntPtr dwExtraInfo; } private delegate IntPtr LowLevelKeyboardProc(int code,IntPtr wParam,IntPtr lParam);
        [DllImport("user32.dll", SetLastError=true)] private static extern IntPtr SetWindowsHookEx(int idHook,LowLevelKeyboardProc proc,IntPtr module,uint threadId); [DllImport("user32.dll")] private static extern bool UnhookWindowsHookEx(IntPtr hook); [DllImport("user32.dll")] private static extern IntPtr CallNextHookEx(IntPtr hook,int code,IntPtr wParam,IntPtr lParam); [DllImport("kernel32.dll", CharSet=CharSet.Unicode)] private static extern IntPtr GetModuleHandle(string name); [DllImport("user32.dll")] private static extern bool PostMessage(IntPtr hWnd,uint msg,IntPtr wParam,IntPtr lParam);
        [DllImport("user32.dll")] private static extern bool RegisterHotKey(IntPtr hWnd,int id,uint fsModifiers,uint vk); [DllImport("user32.dll")] private static extern bool UnregisterHotKey(IntPtr hWnd,int id); [DllImport("user32.dll", SetLastError=true)] private static extern uint SendInput(uint n,ref INPUT i,int size); [DllImport("user32.dll", EntryPoint="SendInput", SetLastError=true)] private static extern uint SendInputBatch(uint n,[In] INPUT[] inputs,int size); [DllImport("user32.dll")] private static extern IntPtr GetForegroundWindow(); [DllImport("user32.dll")] private static extern short GetAsyncKeyState(int vKey); [DllImport("user32.dll")] private static extern uint GetClipboardSequenceNumber(); [DllImport("user32.dll", CharSet=CharSet.Unicode)] private static extern short VkKeyScan(char ch);
    }

    internal sealed class PasterApplicationContext : ApplicationContext
    {
        private readonly TransferCoordinator coordinator; private readonly PasterConfig config; private readonly string configPath; private readonly WindowsPlatform platform; private readonly ManagementPipe pipe; private readonly Control dispatcher; private readonly object workerGate=new object(); private readonly List<Thread> workers=new List<Thread>(); private volatile int transferFailedTick; private volatile bool transferFailed;
        public PasterApplicationContext(WindowsPlatform p, TransferCoordinator c, PasterConfig cfg, string path) { platform=p; coordinator=c; config=cfg; configPath=path; dispatcher=new Control();dispatcher.CreateControl(); platform.CaptureRequested += delegate { StartWorker(delegate { try { coordinator.Capture(); } catch(Exception ex) { coordinator.ReportError(ex.Message); } }); }; platform.PasteRequested += delegate(bool codeMode) { if (coordinator.Status.IsTransferring || transferFailed && unchecked(Environment.TickCount-transferFailedTick) < 1000) return; StartWorker(delegate { WindowsPlatform.SetHighResolutionTimer(true); try { if (!platform.WaitForPasteShortcutRelease()) { coordinator.ReportError("Paste shortcut keys were not released."); return; } if (!coordinator.Transfer(codeMode)) { transferFailedTick=Environment.TickCount; transferFailed=true; } } catch(Exception ex) { coordinator.ReportError(ex.Message); } finally { WindowsPlatform.SetHighResolutionTimer(false); } }); }; platform.CancelRequested += delegate { coordinator.Cancel(); }; pipe=new ManagementPipe(this); }
        public void DispatchCommand(string command) { if(dispatcher.IsDisposed) return; try { dispatcher.BeginInvoke((MethodInvoker)delegate { Command(command); }); } catch(InvalidOperationException) { } }
        public void Command(string command) { if (command=="settings") Management.ShowSettings(config,configPath); else if(command=="status") Management.ShowStatus(coordinator); else if(command=="clear") coordinator.Clear(); else if(command=="exit") ExitThread(); else if(command=="enable-autostart") Management.SetAutostart(true); else if(command=="disable-autostart") Management.SetAutostart(false); }
        private void StartWorker(ThreadStart action) { Thread t=null;t=new Thread((ThreadStart)delegate { try { action(); } finally { lock(workerGate) workers.Remove(Thread.CurrentThread); } });t.IsBackground=true;t.SetApartmentState(ApartmentState.STA);lock(workerGate) workers.Add(t);t.Start(); }
        protected override void ExitThreadCore() { coordinator.Cancel(); Thread[] active;lock(workerGate) active=workers.ToArray();for(int i=0;i<active.Length;i++) active[i].Join(2500);pipe.Dispose();dispatcher.Dispose();base.ExitThreadCore(); }
    }
}
