using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Threading;
using System.Windows.Forms;
using Paster.Core;

namespace Paster.Windows
{
    internal sealed class WindowsPlatform : NativeWindow, ITextCapturePlatform, IDisposable
    {
        private const uint MOD_ALT=1, MOD_CONTROL=2, MOD_SHIFT=4, MOD_WIN=8, MOD_NOREPEAT=0x4000, WM_HOTKEY=0x0312, KEYEVENTF_UNICODE=4, KEYEVENTF_KEYUP=2;
        private const int HOT_CAPTURE=1, HOT_PASTE=2, HOT_CANCEL=3; private readonly PasterConfig config; private string registrationError; private volatile bool inputAvailable=true;
        public event Action CaptureRequested; public event Action PasteRequested; public event Action CancelRequested;
        public WindowsPlatform(PasterConfig c) { config = c; CreateHandle(new CreateParams()); Register(config.CaptureShortcut, HOT_CAPTURE); Register(config.PasteShortcut, HOT_PASTE); Register(config.CancelShortcut, HOT_CANCEL); }
        public string RegistrationError { get { return registrationError; } }
        public IntPtr ForegroundWindow { get { return GetForegroundWindow(); } }
        public uint ClipboardSequence { get { return GetClipboardSequenceNumber(); } }
        public bool IsInputAvailable { get { return inputAvailable; } }
        public bool IsUserInterruptionRequested { get { return UserKeyDown() || MouseButtonDown(); } }
        public void ReleasePasteShortcut() { Paster.Core.Shortcut shortcut=Paster.Core.Shortcut.Parse(config.PasteShortcut); INPUT[] inputs=new INPUT[5]; int count=0; inputs[count++]=CreateInput((ushort)shortcut.Key,0,KEYEVENTF_KEYUP); if ((shortcut.Modifiers & MOD_WIN)!=0) inputs[count++]=CreateInput(0x5B,0,KEYEVENTF_KEYUP); if ((shortcut.Modifiers & MOD_ALT)!=0) inputs[count++]=CreateInput(0x12,0,KEYEVENTF_KEYUP); if ((shortcut.Modifiers & MOD_CONTROL)!=0) inputs[count++]=CreateInput(0x11,0,KEYEVENTF_KEYUP); if ((shortcut.Modifiers & MOD_SHIFT)!=0) inputs[count++]=CreateInput(0x10,0,KEYEVENTF_KEYUP); SendBatch(inputs,count,"paste shortcut release"); }
        public bool SendCopyShortcut() { Paster.Core.Shortcut capture=Paster.Core.Shortcut.Parse(config.CaptureShortcut); bool captureUsesCopy=capture.Modifiers==MOD_CONTROL && capture.Key==0x43; if(captureUsesCopy) UnregisterHotKey(Handle,HOT_CAPTURE); try { if (!ReleaseModifiers()) return false; if (!SendKey(0x11, false)) return false; if (!SendKey(0x43, false)) { SendKey(0x11, true); return false; } if (!SendKey(0x43, true)) { SendKey(0x11, true); return false; } return SendKey(0x11, true); } finally { if(captureUsesCopy) Register(config.CaptureShortcut,HOT_CAPTURE); } }
        public bool TryReadClipboard(out string text) { text = null; try { if (Clipboard.ContainsText(TextDataFormat.UnicodeText)) { text = Clipboard.GetText(TextDataFormat.UnicodeText); return true; } } catch { } return false; }
        public bool SendTextUnit(string unit) { if (unit == "\n") return SendVirtualKeyPair(0x0D); if (unit == "\t") return SendVirtualKeyPair(0x09); if (unit.Length == 0) return true; for (int i=0; i<unit.Length; i++) { short mapped=VkKeyScan(unit[i]); if (mapped != -1) { SendMappedKey(mapped); continue; } INPUT[] unicode=new INPUT[2]; unicode[0]=CreateInput(0,unit[i],KEYEVENTF_UNICODE); unicode[1]=CreateInput(0,unit[i],KEYEVENTF_UNICODE|KEYEVENTF_KEYUP); SendBatch(unicode,2,"Unicode input"); } return true; }
        private bool SendVirtualKeyPair(ushort key) { INPUT[] inputs=new INPUT[2]; inputs[0]=CreateInput(key,0,0); inputs[1]=CreateInput(key,0,KEYEVENTF_KEYUP); SendBatch(inputs,2,"virtual-key input"); return true; }
        private void SendMappedKey(short mapped) { ushort key=(ushort)(mapped & 0xff); int modifiers=(mapped >> 8) & 0xff; bool shift=(modifiers & 1)!=0, control=(modifiers & 2)!=0, alt=(modifiers & 4)!=0; INPUT[] inputs=new INPUT[8]; int count=0; if (shift) inputs[count++]=CreateInput(0x10,0,0); if (control) inputs[count++]=CreateInput(0x11,0,0); if (alt) inputs[count++]=CreateInput(0x12,0,0); inputs[count++]=CreateInput(key,0,0); inputs[count++]=CreateInput(key,0,KEYEVENTF_KEYUP); if (alt) inputs[count++]=CreateInput(0x12,0,KEYEVENTF_KEYUP); if (control) inputs[count++]=CreateInput(0x11,0,KEYEVENTF_KEYUP); if (shift) inputs[count++]=CreateInput(0x10,0,KEYEVENTF_KEYUP); try { SendBatch(inputs,count,"mapped keyboard input"); } catch { ReleaseKeyBestEffort(key); if (shift) ReleaseKeyBestEffort(0x10); if (control) ReleaseKeyBestEffort(0x11); if (alt) ReleaseKeyBestEffort(0x12); throw; } }
        private void ReleaseKeyBestEffort(ushort key) { INPUT input=CreateInput(key,0,KEYEVENTF_KEYUP); try { SendInput(1,ref input,Marshal.SizeOf(typeof(INPUT))); } catch { } }
        private static INPUT CreateInput(ushort key, ushort scan, uint flags) { INPUT input=new INPUT(); input.type=1; input.ki.wVk=key; input.ki.wScan=scan; input.ki.dwFlags=flags; return input; }
        private void SendBatch(INPUT[] inputs, int count, string kind) { if (SendInputBatch((uint)count,inputs,Marshal.SizeOf(typeof(INPUT))) != (uint)count) { inputAvailable=false; throw InputError(kind); } }
        private static Win32Exception InputError(string kind) { int code=Marshal.GetLastWin32Error(); return new Win32Exception(code, "Windows rejected "+kind+" (error "+code+")"); }
        private bool SendKey(ushort key, bool release) { INPUT i=new INPUT(); i.type=1; i.ki.wVk=key; i.ki.dwFlags=release ? KEYEVENTF_KEYUP : 0; bool sent=SendInput(1,ref i,Marshal.SizeOf(typeof(INPUT))) == 1; if(!sent) inputAvailable=false; return sent; }
        private bool ReleaseModifiers() { Stopwatch elapsed=Stopwatch.StartNew(); while (elapsed.ElapsedMilliseconds < 5000 && ModifiersDown()) Thread.Sleep(5); return !ModifiersDown(); }
        private static bool ModifiersDown() { return (GetAsyncKeyState(0x11)&0x8000)!=0 || (GetAsyncKeyState(0x12)&0x8000)!=0 || (GetAsyncKeyState(0x10)&0x8000)!=0 || (GetAsyncKeyState(0x5B)&0x8000)!=0 || (GetAsyncKeyState(0x5C)&0x8000)!=0; }
        private bool UserKeyDown() { Paster.Core.Shortcut paste=Paster.Core.Shortcut.Parse(config.PasteShortcut); for (int key = 1; key <= 0xFE; key++) { if (IsMouseButton(key) || key == (int)paste.Key || (key == 0x10 || key == 0xA0 || key == 0xA1) && (paste.Modifiers & MOD_SHIFT) != 0 || (key == 0x11 || key == 0xA2 || key == 0xA3) && (paste.Modifiers & MOD_CONTROL) != 0 || (key == 0x12 || key == 0xA4 || key == 0xA5) && (paste.Modifiers & MOD_ALT) != 0 || (key == 0x5B || key == 0x5C) && (paste.Modifiers & MOD_WIN) != 0) continue; if ((GetAsyncKeyState(key) & 0x8000) != 0) return true; } return false; }
        private static bool IsMouseButton(int key) { return key==0x01 || key==0x02 || key==0x04 || key==0x05 || key==0x06; }
        private static bool MouseButtonDown() { return (GetAsyncKeyState(0x01)&0x8001)!=0 || (GetAsyncKeyState(0x02)&0x8001)!=0 || (GetAsyncKeyState(0x04)&0x8001)!=0 || (GetAsyncKeyState(0x05)&0x8001)!=0 || (GetAsyncKeyState(0x06)&0x8001)!=0; }
        private void Register(string value, int id) { Paster.Core.Shortcut s=Paster.Core.Shortcut.Parse(value); if (!RegisterHotKey(Handle,id,s.Modifiers|MOD_NOREPEAT,s.Key)) { string error="Shortcut registration failed for "+value+".";registrationError=String.IsNullOrEmpty(registrationError)?error:registrationError+" "+error; } }
        protected override void WndProc(ref Message m) { if (m.Msg==WM_HOTKEY) { int id=m.WParam.ToInt32(); if(id==HOT_CAPTURE && CaptureRequested!=null) CaptureRequested(); else if(id==HOT_PASTE && PasteRequested!=null) PasteRequested(); else if(id==HOT_CANCEL && CancelRequested!=null) CancelRequested(); } base.WndProc(ref m); }
        public void Dispose() { UnregisterHotKey(Handle,HOT_CAPTURE); UnregisterHotKey(Handle,HOT_PASTE); UnregisterHotKey(Handle,HOT_CANCEL); DestroyHandle(); }
        [StructLayout(LayoutKind.Sequential)] private struct INPUT { public uint type; public KEYBDINPUT ki; private uint padding1; private uint padding2; } [StructLayout(LayoutKind.Sequential)] private struct KEYBDINPUT { public ushort wVk,wScan; public uint dwFlags,time; public UIntPtr dwExtraInfo; }
        [DllImport("user32.dll")] private static extern bool RegisterHotKey(IntPtr hWnd,int id,uint fsModifiers,uint vk); [DllImport("user32.dll")] private static extern bool UnregisterHotKey(IntPtr hWnd,int id); [DllImport("user32.dll", SetLastError=true)] private static extern uint SendInput(uint n,ref INPUT i,int size); [DllImport("user32.dll", EntryPoint="SendInput", SetLastError=true)] private static extern uint SendInputBatch(uint n,[In] INPUT[] inputs,int size); [DllImport("user32.dll")] private static extern IntPtr GetForegroundWindow(); [DllImport("user32.dll")] private static extern short GetAsyncKeyState(int vKey); [DllImport("user32.dll")] private static extern uint GetClipboardSequenceNumber(); [DllImport("user32.dll", CharSet=CharSet.Unicode)] private static extern short VkKeyScan(char ch);
    }

    internal sealed class PasterApplicationContext : ApplicationContext
    {
        private readonly TransferCoordinator coordinator; private readonly PasterConfig config; private readonly string configPath; private readonly WindowsPlatform platform; private readonly ManagementPipe pipe; private readonly Control dispatcher; private readonly object workerGate=new object(); private readonly List<Thread> workers=new List<Thread>();
        public PasterApplicationContext(WindowsPlatform p, TransferCoordinator c, PasterConfig cfg, string path) { platform=p; coordinator=c; config=cfg; configPath=path; dispatcher=new Control();dispatcher.CreateControl(); platform.CaptureRequested += delegate { StartWorker(delegate { try { coordinator.Capture(); } catch(Exception ex) { coordinator.ReportError(ex.Message); } }); }; platform.PasteRequested += delegate { StartWorker(delegate { try { platform.ReleasePasteShortcut(); coordinator.Transfer(); } catch(Exception ex) { coordinator.ReportError(ex.Message); } }); }; platform.CancelRequested += delegate { coordinator.Cancel(); }; pipe=new ManagementPipe(this); }
        public void DispatchCommand(string command) { if(dispatcher.IsDisposed) return; try { dispatcher.BeginInvoke((MethodInvoker)delegate { Command(command); }); } catch(InvalidOperationException) { } }
        public void Command(string command) { if (command=="settings") Management.ShowSettings(config,configPath); else if(command=="status") Management.ShowStatus(coordinator); else if(command=="clear") coordinator.Clear(); else if(command=="exit") ExitThread(); else if(command=="enable-autostart") Management.SetAutostart(true); else if(command=="disable-autostart") Management.SetAutostart(false); }
        private void StartWorker(ThreadStart action) { Thread t=null;t=new Thread((ThreadStart)delegate { try { action(); } finally { lock(workerGate) workers.Remove(Thread.CurrentThread); } });t.IsBackground=true;t.SetApartmentState(ApartmentState.STA);lock(workerGate) workers.Add(t);t.Start(); }
        protected override void ExitThreadCore() { coordinator.Cancel(); Thread[] active;lock(workerGate) active=workers.ToArray();for(int i=0;i<active.Length;i++) active[i].Join(2500);pipe.Dispose();dispatcher.Dispose();base.ExitThreadCore(); }
    }
}
