using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Threading;
using Paster.Core;

namespace Paster.CoreTests
{
    internal sealed class FakePlatform : ITextCapturePlatform
    {
        public IntPtr ForegroundWindow = new IntPtr(1); public bool CopyWorks = true; public string Clipboard; public bool InputWorks = true; public bool ChangeAfterFirst; public bool UserInterruption; public int InterruptAfterUnits = -1; public bool Remote; public TransferChoice Choice = TransferChoice.Start; public List<TransferPrompt> Prompts = new List<TransferPrompt>(); public uint Sequence; public List<string> Units = new List<string>();
        IntPtr ITextCapturePlatform.ForegroundWindow { get { return (ChangeAfterFirst && Units.Count > 0) ? new IntPtr(2) : ForegroundWindow; } }
        public bool IsInputAvailable { get { return InputWorks; } }
        public uint ClipboardSequence { get { return Sequence; } }
        public bool SendCopyShortcut() { if (CopyWorks) Sequence++; return CopyWorks; }
        public bool TryReadClipboard(out string text) { text = Clipboard; return text != null; }
        public bool SendText(string text) { if (!InputWorks) return false; Units.Add(text); return true; }
        public bool IsUserInterruptionRequested { get { return UserInterruption || InterruptAfterUnits >= 0 && Units.Count >= InterruptAfterUnits; } }
        public TransferChoice ConfirmTransfer(TransferPrompt prompt) { Prompts.Add(prompt); return Choice; }
        public bool IsRemoteWindow(IntPtr window) { return Remote; }
    }
    internal sealed class FakeClock : IClock { public Action<int> OnSleep; public List<int> Sleeps = new List<int>(); private bool fired; public void Sleep(int milliseconds, CancellationToken token) { Sleeps.Add(milliseconds); token.ThrowIfCancellationRequested(); if(!fired && OnSleep!=null) { fired=true; OnSleep(milliseconds); } token.ThrowIfCancellationRequested(); } }
    internal static class Program
    {
        private static int passed;
        private static void Assert(bool value, string message) { if (!value) throw new Exception(message); }
        private static void Test(string name, Action action) { action(); passed++; Console.WriteLine("PASS "+name); }
        public static int Main()
        {
            Test("capture and structured transfer", delegate { FakePlatform p=new FakePlatform(); p.Clipboard="{\"x\": 1}\nitems:\n\t- café\n\npunctuation: !?"; TransferCoordinator c=new TransferCoordinator(p,new FakeClock(),new PasterConfig()); Assert(c.Capture(),"capture"); Assert(c.Transfer(),"transfer"); Assert(String.Join("",p.Units.ToArray()).Contains("café"),"unicode"); });
            Test("capture failure clears stale text", delegate { FakePlatform p=new FakePlatform(); p.Clipboard="old"; TransferCoordinator c=new TransferCoordinator(p,new FakeClock(),new PasterConfig()); Assert(c.Capture(),"first"); p.CopyWorks=false; Assert(!c.Capture(),"failure"); Assert(!c.Status.HasCapture,"stale capture"); });
            Test("size limit", delegate { FakePlatform p=new FakePlatform(); p.Clipboard="12345"; PasterConfig cfg=new PasterConfig(); cfg.MaximumTextCharacters=3; TransferCoordinator c=new TransferCoordinator(p,new FakeClock(),cfg); Assert(!c.Capture(),"limit"); });
            Test("invalid batch settings rejected", delegate { PasterConfig delay=new PasterConfig(); delay.CharacterDelayMilliseconds=-1; PasterConfig batch=new PasterConfig(); batch.CharactersPerBatch=0; bool delayRejected=false, batchRejected=false; try { delay.Validate(); } catch(ArgumentOutOfRangeException) { delayRejected=true; } try { batch.Validate(); } catch(ArgumentOutOfRangeException) { batchRejected=true; } Assert(delayRejected && batchRejected,"invalid batch settings accepted"); });
            Test("text is sent in batches with normalized line endings", delegate { FakePlatform p=new FakePlatform(); p.Clipboard="ab\r\ncd\ref\ng"; PasterConfig cfg=new PasterConfig(); cfg.CharactersPerBatch=3; TransferCoordinator c=new TransferCoordinator(p,new FakeClock(),cfg); Assert(c.Transfer(),"transfer"); Assert(String.Join("|",p.Units.ToArray())=="ab\n|cd\n|ef\n|g","batches: "+String.Join("|",p.Units.ToArray())); });
            Test("batches never split surrogate pairs", delegate { FakePlatform p=new FakePlatform(); p.Clipboard="a\U0001F600b"; PasterConfig cfg=new PasterConfig(); cfg.CharactersPerBatch=2; TransferCoordinator c=new TransferCoordinator(p,new FakeClock(),cfg); Assert(c.Transfer(),"transfer"); Assert(p.Units.Count==2 && p.Units[0]=="a\U0001F600","surrogate split"); });
            Test("settings missing new fields load with defaults", delegate { string path=Path.Combine(Path.GetTempPath(),"paster-test-"+Guid.NewGuid().ToString("N")+".json"); try { File.WriteAllText(path,"{\"captureShortcut\":\"Ctrl+Alt+C\",\"pasteShortcut\":\"Ctrl+Shift+V\",\"cancelShortcut\":\"Ctrl+Shift+X\",\"startDelayMilliseconds\":0,\"characterDelayMilliseconds\":8,\"clipboardTimeoutMilliseconds\":2000,\"maximumTextCharacters\":1048576}",new UTF8Encoding(false)); PasterConfig cfg=PasterConfig.Load(path); Assert(cfg.CaptureShortcut=="Ctrl+Alt+C","custom shortcut lost"); Assert(cfg.CharactersPerBatch==new PasterConfig().CharactersPerBatch,"batch default not applied"); } finally { File.Delete(path); } });
            Test("shortcut parser rejects multiple keys and duplicate modifiers", delegate { bool multiple=false, duplicate=false; try { Shortcut.Parse("Ctrl+C+V"); } catch(FormatException) { multiple=true; } try { Shortcut.Parse("Ctrl+Ctrl+C"); } catch(FormatException) { duplicate=true; } Assert(multiple && duplicate,"ambiguous shortcut accepted"); });
            Test("shortcut parser rejects unsupported virtual keys", delegate { bool unicode=false, punctuation=false; try { Shortcut.Parse("Ctrl+é"); } catch(FormatException) { unicode=true; } try { Shortcut.Parse("Ctrl+!"); } catch(FormatException) { punctuation=true; } Assert(unicode && punctuation,"unsupported shortcut accepted"); });
            Test("conflicting configured shortcuts rejected", delegate { PasterConfig cfg=new PasterConfig(); cfg.PasteShortcut=cfg.CaptureShortcut; bool rejected=false; try { cfg.Validate(); } catch(FormatException) { rejected=true; } Assert(rejected,"conflicting shortcuts accepted"); });
            Test("input availability is enforced", delegate { FakePlatform p=new FakePlatform(); p.Clipboard="abc"; p.InputWorks=false; TransferCoordinator c=new TransferCoordinator(p,new FakeClock(),new PasterConfig()); Assert(!c.Transfer(),"unavailable input transferred"); Assert(!c.Status.IsInputAvailable,"availability status"); });
            Test("clipboard fallback transfer", delegate { FakePlatform p=new FakePlatform(); p.Clipboard="copied normally"; TransferCoordinator c=new TransferCoordinator(p,new FakeClock(),new PasterConfig()); Assert(c.Transfer(),"transfer"); Assert(String.Join("",p.Units.ToArray())==p.Clipboard,"clipboard fallback"); });
            Test("focus change and cancellation", delegate { FakePlatform p=new FakePlatform(); p.Clipboard="abc"; PasterConfig cfg=new PasterConfig(); cfg.CharactersPerBatch=1; TransferCoordinator c=new TransferCoordinator(p,new FakeClock(),cfg); Assert(c.Capture(),"capture"); p.ChangeAfterFirst=true; Assert(!c.Transfer(),"focus stop"); p.ChangeAfterFirst=false; Assert(c.Capture(),"recapture"); c.Cancel(); Assert(!c.Status.IsTransferring,"cancel state"); });
            Test("overlap prevention", delegate { FakePlatform p=new FakePlatform(); p.Clipboard="abc"; TransferCoordinator c=new TransferCoordinator(p,new FakeClock(),new PasterConfig()); Assert(c.Capture(),"capture"); Assert(c.Transfer(),"transfer"); Assert(!c.Status.IsTransferring,"finished"); });
            Test("user interruption stops transfer and preserves capture", delegate { FakePlatform p=new FakePlatform(); p.Clipboard="abc"; TransferCoordinator c=new TransferCoordinator(p,new FakeClock(),new PasterConfig()); Assert(c.Capture(),"capture"); p.UserInterruption=true; Assert(!c.Transfer(),"interruption ignored"); Assert(!c.Status.IsTransferring,"transfer still active"); Assert(c.Status.HasCapture,"valid capture discarded"); });
            Test("capture is rejected during transfer", delegate { FakePlatform p=new FakePlatform(); p.Clipboard="abc"; FakeClock clock=new FakeClock(); TransferCoordinator c=new TransferCoordinator(p,clock,new PasterConfig()); Assert(c.Capture(),"capture"); bool overlappingCapture=true; clock.OnSleep=delegate(int ignored) { overlappingCapture=c.Capture(); }; Assert(c.Transfer(),"transfer"); Assert(!overlappingCapture,"overlapping capture accepted"); Assert(c.Status.HasCapture,"capture lost after overlap rejection"); });
            Test("newer clipboard text wins over an older capture", delegate { FakePlatform p=new FakePlatform(); p.Clipboard="captured"; TransferCoordinator c=new TransferCoordinator(p,new FakeClock(),new PasterConfig()); Assert(c.Capture(),"capture"); Assert(c.Transfer(),"transfer"); Assert(String.Join("",p.Units.ToArray())=="captured","capture not used"); p.Units.Clear(); p.Clipboard="copied later"; p.Sequence++; Assert(c.Transfer(),"second transfer"); Assert(String.Join("",p.Units.ToArray())=="copied later","newer clipboard ignored"); });
            Test("capture is kept when the clipboard changes to non-text", delegate { FakePlatform p=new FakePlatform(); p.Clipboard="captured"; TransferCoordinator c=new TransferCoordinator(p,new FakeClock(),new PasterConfig()); Assert(c.Capture(),"capture"); p.Clipboard=null; p.Sequence++; Assert(c.Transfer(),"transfer"); Assert(String.Join("",p.Units.ToArray())=="captured","capture lost"); });
            Test("type-on-paste app matching", delegate { PasterConfig cfg=new PasterConfig(); Assert(cfg.IsTypeOnPasteApp(@"C:\Windows\System32\mstsc.exe",null),"full path"); Assert(cfg.IsTypeOnPasteApp("MSRDC","x"),"name without extension"); Assert(!cfg.IsTypeOnPasteApp("notepad.exe","Windows Cloud"),"unlisted app matched"); Assert(!cfg.IsTypeOnPasteApp(null,null),"null matched"); cfg.TypeOnPasteApps="vmconnect; wfica32.exe"; Assert(cfg.IsTypeOnPasteApp("vmconnect.exe",null) && cfg.IsTypeOnPasteApp("wfica32.exe",null) && !cfg.IsTypeOnPasteApp("mstsc.exe",null),"custom list"); cfg.TypeOnPasteApps=""; Assert(!cfg.IsTypeOnPasteApp("mstsc.exe",null),"empty list matched"); });
            Test("browser clients match only by window title", delegate { PasterConfig cfg=new PasterConfig(); Assert(cfg.IsTypeOnPasteApp(@"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe","Windows Cloud - Energinet AVD Windows 11"),"web client not matched"); Assert(!cfg.IsTypeOnPasteApp("msedge.exe","Inbox - Outlook"),"ordinary browser tab matched"); Assert(!cfg.IsTypeOnPasteApp("msedge.exe",null),"untitled browser matched"); });
            Test("remote targets are paced in small batches", delegate { FakePlatform p=new FakePlatform(); p.Clipboard="abcdefg"; p.Remote=true; PasterConfig cfg=new PasterConfig(); cfg.RemoteCharactersPerSecond=300; TransferCoordinator c=new TransferCoordinator(p,new FakeClock(),cfg); Assert(c.Transfer(),"transfer"); Assert(String.Join("|",p.Units.ToArray())=="abc|def|g","remote batches: "+String.Join("|",p.Units.ToArray())); p.Units.Clear(); cfg.RemoteCharactersPerSecond=0; Assert(c.Transfer(),"unlimited transfer"); Assert(p.Units.Count==1,"unlimited remote speed still paced"); });
            Test("interrupted large transfer resumes where it stopped", delegate { FakePlatform p=new FakePlatform(); p.Clipboard="ab\ncd"; p.InterruptAfterUnits=1; PasterConfig cfg=new PasterConfig(); cfg.CharactersPerBatch=2; cfg.ConfirmAboveLines=1; TransferCoordinator c=new TransferCoordinator(p,new FakeClock(),cfg); Assert(!c.Transfer(),"interruption ignored"); Assert(c.Status.ResumeOffset==2 && c.Status.ResumeTotal==5,"resume point "+c.Status.ResumeOffset); p.Units.Clear(); p.InterruptAfterUnits=-1; p.Prompts.Clear(); p.Choice=TransferChoice.Resume; Assert(c.Transfer(),"resume"); Assert(p.Prompts.Count==1 && p.Prompts[0].ResumeOffset==2,"resume prompt"); Assert(String.Join("|",p.Units.ToArray())=="\nc|d","resumed units: "+String.Join("|",p.Units.ToArray())); Assert(c.Status.ResumeOffset==0,"resume point kept after success"); });
            Test("start over and cancel at the resume prompt", delegate { FakePlatform p=new FakePlatform(); p.Clipboard="ab\ncd"; p.InterruptAfterUnits=1; PasterConfig cfg=new PasterConfig(); cfg.CharactersPerBatch=2; cfg.ConfirmAboveLines=1; TransferCoordinator c=new TransferCoordinator(p,new FakeClock(),cfg); Assert(!c.Transfer(),"interruption ignored"); p.Units.Clear(); p.InterruptAfterUnits=-1; p.Choice=TransferChoice.Cancel; Assert(!c.Transfer(),"cancel typed"); Assert(p.Units.Count==0 && c.Status.ResumeOffset==2,"cancel lost resume point"); p.Choice=TransferChoice.Start; Assert(c.Transfer(),"start over"); Assert(String.Join("",p.Units.ToArray())=="ab\ncd","start over did not type everything"); });
            Test("short texts never prompt and restart after an interruption", delegate { FakePlatform p=new FakePlatform(); p.Clipboard="abcdef"; p.InterruptAfterUnits=1; PasterConfig cfg=new PasterConfig(); cfg.CharactersPerBatch=2; TransferCoordinator c=new TransferCoordinator(p,new FakeClock(),cfg); Assert(!c.Transfer(),"interruption ignored"); Assert(c.Status.ResumeOffset==0,"resume point saved for short text"); p.Units.Clear(); p.InterruptAfterUnits=-1; Assert(c.Transfer(),"transfer"); Assert(p.Prompts.Count==0 && String.Join("",p.Units.ToArray())=="abcdef","short text prompted or resumed"); });
            Test("only texts over the line threshold ask first", delegate { FakePlatform p=new FakePlatform(); p.Remote=true; p.Clipboard="x\ny\nz"; PasterConfig cfg=new PasterConfig(); cfg.RemoteCharactersPerSecond=100; cfg.ConfirmAboveLines=2; TransferCoordinator c=new TransferCoordinator(p,new FakeClock(),cfg); p.Choice=TransferChoice.Cancel; Assert(!c.Transfer(),"declined transfer typed"); Assert(p.Prompts.Count==1 && p.Units.Count==0,"no prompt for large text"); Assert(p.Prompts[0].Message.Contains("3 lines") && p.Prompts[0].Message.Contains("remote session"),"prompt text: "+p.Prompts[0].Message); p.Clipboard="a\nb"; p.Sequence++; Assert(c.Transfer(),"text at threshold"); Assert(p.Prompts.Count==1,"text at threshold prompted"); cfg.ConfirmAboveLines=0; p.Clipboard="x\ny\nz\nw"; p.Sequence++; Assert(c.Transfer(),"threshold 0"); Assert(p.Prompts.Count==1,"threshold 0 still prompted"); });
            Test("resumed remote transfer is paced from the resume point", delegate { FakePlatform p=new FakePlatform(); p.Remote=true; p.Clipboard=new string('x',399)+"\n"; p.InterruptAfterUnits=300; PasterConfig cfg=new PasterConfig(); cfg.RemoteCharactersPerSecond=100; cfg.ConfirmAboveLines=1; FakeClock clock=new FakeClock(); TransferCoordinator c=new TransferCoordinator(p,clock,cfg); Assert(!c.Transfer(),"interruption ignored"); Assert(c.Status.ResumeOffset==300,"resume point "+c.Status.ResumeOffset); p.Units.Clear(); p.InterruptAfterUnits=-1; p.Choice=TransferChoice.Resume; clock.Sleeps.Clear(); Assert(c.Transfer(),"resume"); Assert(p.Units.Count==100,"resumed units "+p.Units.Count); Assert(clock.Sleeps.Count>1 && clock.Sleeps[1]<=15,"first paced wait after resume: "+clock.Sleeps[1]); });
            Test("estimate respects the batch delay floor", delegate { FakePlatform p=new FakePlatform(); p.Remote=true; p.Clipboard=new string('x',99999)+"\n"; PasterConfig cfg=new PasterConfig(); cfg.RemoteCharactersPerSecond=100000; cfg.CharactersPerBatch=10; cfg.CharacterDelayMilliseconds=10; cfg.ConfirmAboveLines=1; TransferCoordinator c=new TransferCoordinator(p,new FakeClock(),cfg); p.Choice=TransferChoice.Cancel; Assert(!c.Transfer(),"declined"); Assert(p.Prompts.Count==1 && p.Prompts[0].Message.Contains("about 2 minutes"),"estimate ignored delay floor: "+(p.Prompts.Count>0?p.Prompts[0].Message:"no prompt")); });
            Test("pasting different text discards the resume point even when declined", delegate { FakePlatform p=new FakePlatform(); p.Clipboard="ab\ncd"; p.InterruptAfterUnits=1; PasterConfig cfg=new PasterConfig(); cfg.CharactersPerBatch=2; cfg.ConfirmAboveLines=1; TransferCoordinator c=new TransferCoordinator(p,new FakeClock(),cfg); Assert(!c.Transfer(),"interruption ignored"); Assert(c.Status.ResumeOffset==2,"resume point"); p.InterruptAfterUnits=-1; p.Clipboard="gh\nij"; p.Sequence++; p.Choice=TransferChoice.Cancel; Assert(!c.Transfer(),"declined"); Assert(c.Status.ResumeOffset==0,"resume point kept for other text"); });
            Test("duration descriptions", delegate { Assert(TransferPrompt.Describe(TimeSpan.FromSeconds(0.2))=="about 1 second","sub-second"); Assert(TransferPrompt.Describe(TimeSpan.FromSeconds(45))=="about 45 seconds","seconds"); Assert(TransferPrompt.Describe(TimeSpan.FromSeconds(480))=="about 8 minutes","minutes"); Assert(TransferPrompt.Describe(TimeSpan.FromMinutes(125))=="about 2 hours 5 minutes","hours"); });
            Test("maximum text limit raised to 256M", delegate { PasterConfig ok=new PasterConfig(); ok.MaximumTextCharacters=PasterConfig.MaximumTextLimit; ok.Validate(); PasterConfig tooBig=new PasterConfig(); tooBig.MaximumTextCharacters=PasterConfig.MaximumTextLimit+1; bool rejected=false; try { tooBig.Validate(); } catch(ArgumentOutOfRangeException) { rejected=true; } Assert(rejected,"limit not enforced"); });
            Console.WriteLine("{0} tests passed", passed); return 0;
        }
    }
}
